# wrangler.toml
name = 'little-mode-3fa0'
type = "javascript"

workers_dev = true
#route = ""
#zone_id = ""
compatibility_date = "2021-11-19"
main = "worker-multple.js"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
WEBHOOK_SECRET="secret"
CF_CLIENT_ID="Client Auth ID"
CF_CLIENT_SECRET="Client Secret"
SERVICE_URLS=https://testing-webhook.rocket.chat/hooks/XXX
https://testing-webhook.rocket.chat/hooks/XXX2

[env.production.vars]
WEBHOOK_SECRET="production-secret"
CF_CLIENT_ID="Client Auth ID"
CF_CLIENT_SECRET="Client Secret"
SERVICE_URLS="https://testing-webhook.rocket.chat/hooks/XXX"
