# wrangler.toml
name = 'little-mode-3fa0'
type = "javascript"

workers_dev = true
#route = ""
#zone_id = ""
compatibility_date = "2021-11-19"
main = "worker-multiple.js"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
SERVICE_URLS = "api.example.com"
WEBHOOK_SECRET = "secret"
CF_CLIENT_ID = "client id"
CF_CLIENT_SECRET = "client secret"
